### ISSUE TITLE
Missing titles and styles

### ISSUE THREAD

**Issue by kgp43** [Proxeuse/fortify-tabler#4]
Hi,

Thanks for this package - makes it quite easy to get started :)
Got a few problems though.

- Fresh laravel installation.
- Followed the install guide step-by-step: https://www.proxeuse.com/en/2020/use-laravel-jetstream-with-bootstrap/

I'm not able to see the "change password" titles and the 2FA button is also looking weird.
Rest seems fine.

What can be the reason for this?

![image](https://user-images.githubusercontent.com/15347427/103170436-7dc57280-4844-11eb-8bfb-ab795eeb80fc.png)

**Comment by roelreijneveld** [comment]
Hi @kgp43

Thanks for pointing out those mistakes!

I've released a new version ([v1.1.1](https://github.com/Proxeuse/fortify-tabler/releases/tag/v1.1.1)) which fixes those issues. You should be able to install those updates by running `composer update` and `php artisan fortify-ui:tabler-update`. Please note that running the second command will override certain files previously installed by the installer.

Please let me know if you have any further questions!

**Comment by kgp43** [comment]
Hi Roel,

That was fast and worked perfectly! 
Thanks a lot for the detailed update instructions.

Love this package :)

**Comment by kgp43** [comment]
Hi @RoelReijn 

I found one more minor bug (very small).
It seems there is missing a closing div on this part within the home view:

`<div class="card-body">
                        <div class="alert alert-success">
                        Hi there! Thank you for using the ....
                    </div>`

This: `<div class="alert alert-success">` does not have a closing div.
If I add a closing div, then the footer is moved down a bit.

It works fine as it is, but my editor (VS Code) tells me the page is missing a closing div (home.blade.php)

**Comment by roelreijneveld** [comment]
Hi @kgp43 

> Hi Roel,
> 
> That was fast and worked perfectly!
> Thanks a lot for the detailed update instructions.
> 
> Love this package :)

Thanks a lot!

> Hi RoelReijn
> 
> I found one more minor bug (very small).
> It seems there is missing a closing div on this part within the home view:
> 
> `<div class="card-body"> <div class="alert alert-success"> Hi there! Thank you for using the .... </div>`
> 
> This: `<div class="alert alert-success">` does not have a closing div.
> If I add a closing div, then the footer is moved down a bit.
> 
> It works fine as it is, but my editor (VS Code) tells me the page is missing a closing div (home.blade.php)

Thanks for noticing. I'm about to release a new version which includes a bug fix. Please note that the update command has changed to `php artisan tabler:update --type=full` as you will be able to see in the README.md file.

I will close this issue now but please open a new issue if you find other bugs or if you have ideas for a new feature.
